#!/usr/bin/env bash
set -Eeuo pipefail

# Ghostty developer setup for macOS
# Safe to run repeatedly: existing configs are backed up, and the managed
# ~/.zshrc block is replaced instead of duplicated.

if [[ "$(uname -s)" != "Darwin" ]]; then
  echo "This installer is intended for macOS."
  exit 1
fi

timestamp="$(date +%Y%m%d-%H%M%S)"
backup_dir="$HOME/.config/ghostty-dev-setup/backups/$timestamp"

log() {
  printf '\n\033[1;36m==>\033[0m %s\n' "$1"
}

warn() {
  printf '\033[1;33mWarning:\033[0m %s\n' "$1" >&2
}

die() {
  printf '\033[1;31mError:\033[0m %s\n' "$1" >&2
  exit 1
}

backup_file() {
  local source_file="$1"
  if [[ -f "$source_file" ]]; then
    mkdir -p "$backup_dir"
    cp -p "$source_file" "$backup_dir/$(basename "$source_file")"
    echo "Backed up: $source_file"
  fi
}

install_homebrew() {
  if command -v brew >/dev/null 2>&1; then
    return
  fi

  log "Installing Homebrew"
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  if [[ -x /opt/homebrew/bin/brew ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
  elif [[ -x /usr/local/bin/brew ]]; then
    eval "$(/usr/local/bin/brew shellenv)"
  else
    die "Homebrew installation finished, but brew was not found."
  fi
}

install_packages() {
  log "Installing command-line tools"
  brew update

  local formulae=(
    starship
    atuin
    zoxide
    fzf
    eza
    bat
    lazygit
    git-delta
    fd
    ripgrep
    zsh-autosuggestions
    zsh-syntax-highlighting
  )

  brew install "${formulae[@]}"

  log "Installing JetBrainsMono Nerd Font"
  brew install --cask font-jetbrains-mono-nerd-font || \
    warn "The Nerd Font cask could not be installed. The rest of the setup will continue."
}

write_ghostty_config() {
  local ghostty_dir="$HOME/Library/Application Support/com.mitchellh.ghostty"
  local ghostty_config="$ghostty_dir/config.ghostty"
  local old_config="$ghostty_dir/config"

  mkdir -p "$ghostty_dir"
  backup_file "$ghostty_config"
  backup_file "$old_config"

  log "Writing Ghostty configuration"

  cat > "$ghostty_config" <<'GHOSTTY'
# Generated by ghostty-dev-setup.sh

font-family = JetBrainsMono Nerd Font
font-size = 14
font-thicken = true
font-thicken-strength = 40

theme = Catppuccin Mocha
background-opacity = 0.94
background-blur = macos-glass-regular

cursor-style = bar
cursor-style-blink = false
cursor-click-to-move = true
mouse-hide-while-typing = true

window-padding-x = 14
window-padding-y = 12
window-padding-balance = true
window-save-state = always
macos-titlebar-style = tabs

shell-integration = zsh
shell-integration-features = cursor,title,ssh-env,ssh-terminfo

scrollback-limit = 10000000
unfocused-split-opacity = 0.84
split-divider-color = 585b70
split-preserve-zoom = navigation

notify-on-command-finish = unfocused
notify-on-command-finish-action = no-bell,notify
notify-on-command-finish-after = 10s
GHOSTTY

  # Keep one canonical config file.
  if [[ -f "$old_config" ]]; then
    cat > "$old_config" <<'GHOSTTY_REDIRECT'
# This file is intentionally unused.
# Active config: config.ghostty
GHOSTTY_REDIRECT
  fi
}

write_starship_config() {
  local starship_dir="$HOME/.config"
  local starship_config="$starship_dir/starship.toml"

  mkdir -p "$starship_dir"
  backup_file "$starship_config"

  log "Writing Starship configuration"

  cat > "$starship_config" <<'STARSHIP'
"$schema" = "https://starship.rs/config-schema.json"

format = """
[](red)\
$os\
$username\
[](bg:peach fg:red)\
$directory\
[](bg:yellow fg:peach)\
$git_branch\
$git_status\
[](fg:yellow bg:green)\
$nodejs\
$php\
$python\
$rust\
$golang\
[](fg:green bg:sapphire)\
$docker_context\
[](fg:sapphire bg:lavender)\
$time\
[ ](fg:lavender)\
$cmd_duration\
$status\
$line_break\
$character
"""

palette = "catppuccin_mocha"

[os]
disabled = false
style = "bg:red fg:crust"

[os.symbols]
Macos = "󰀵"
Linux = "󰌽"
Windows = ""
Ubuntu = "󰕈"
Debian = "󰣚"

[username]
show_always = true
style_user = "bg:red fg:crust"
style_root = "bg:red fg:crust"
format = "[ $user ]($style)"

[directory]
style = "bg:peach fg:crust"
format = "[ $path ]($style)"
truncation_length = 4
truncation_symbol = "…/"
truncate_to_repo = false
read_only = " 󰌾"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "
"Development" = "󰲋 "
"Herd" = "󰲋 "

[git_branch]
symbol = " "
style = "bg:yellow fg:crust"
format = "[ $symbol$branch(:$remote_branch) ]($style)"

[git_status]
style = "bg:yellow fg:crust"
format = "[$all_status$ahead_behind ]($style)"
conflicted = "=${count} "
ahead = "⇡${count} "
behind = "⇣${count} "
diverged = "⇕⇡${ahead_count}⇣${behind_count} "
up_to_date = "✓ "
untracked = "?${count} "
stashed = "\\$${count} "
modified = "!${count} "
staged = "+${count} "
renamed = "»${count} "
deleted = "✘${count} "

[nodejs]
symbol = ""
style = "bg:green fg:crust"
format = "[ $symbol $version ]($style)"
detect_files = ["package.json", ".node-version", ".nvmrc"]

[php]
symbol = ""
style = "bg:green fg:crust"
format = "[ $symbol $version ]($style)"
detect_files = ["composer.json", ".php-version", "artisan"]

[python]
symbol = ""
style = "bg:green fg:crust"
format = "[ $symbol $version( \\($virtualenv\\)) ]($style)"

[rust]
symbol = ""
style = "bg:green fg:crust"
format = "[ $symbol $version ]($style)"

[golang]
symbol = ""
style = "bg:green fg:crust"
format = "[ $symbol $version ]($style)"

[docker_context]
symbol = ""
style = "bg:sapphire fg:crust"
format = "[ $symbol $context ]($style)"
only_with_files = true

[time]
disabled = false
time_format = "%H:%M"
style = "bg:lavender fg:crust"
format = "[  $time ]($style)"

[cmd_duration]
disabled = false
min_time = 1000
show_milliseconds = false
show_notifications = true
min_time_to_notify = 45000
style = "bold yellow"
format = "[󱦟 $duration]($style) "

[status]
disabled = false
symbol = "✘"
not_executable_symbol = "󰂭"
not_found_symbol = "󰍉"
sigint_symbol = "󰚌"
signal_symbol = "󱐋"
style = "bold red"
format = "[$symbol $status]($style) "
map_symbol = true

[line_break]
disabled = true

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold green)"
vimcmd_replace_one_symbol = "[❮](bold lavender)"
vimcmd_replace_symbol = "[❮](bold lavender)"
vimcmd_visual_symbol = "[❮](bold yellow)"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
STARSHIP
}

write_zsh_config() {
  local zshrc="$HOME/.zshrc"
  local begin_marker="# >>> GHOSTTY DEV SETUP >>>"
  local end_marker="# <<< GHOSTTY DEV SETUP <<<"
  local brew_prefix

  touch "$zshrc"
  backup_file "$zshrc"
  brew_prefix="$(brew --prefix)"

  log "Updating ~/.zshrc"

  # Remove a previous managed block, while preserving everything else.
  awk -v begin="$begin_marker" -v end="$end_marker" '
    $0 == begin { skip = 1; next }
    $0 == end   { skip = 0; next }
    !skip       { print }
  ' "$zshrc" > "$zshrc.tmp"

  mv "$zshrc.tmp" "$zshrc"

  # Disable the Angular completion line that can crash shell startup due to
  # incompatible global Angular CLI/yargs versions.
  sed -i '' -E \
    's|^[[:space:]]*(source[[:space:]]+<\(ng completion script\)|eval[[:space:]]+"\$\(ng completion script\)")|# Disabled by ghostty-dev-setup: \1|' \
    "$zshrc"

  cat >> "$zshrc" <<ZSHRC

$begin_marker

# Homebrew
eval "\$($brew_prefix/bin/brew shellenv)"

# Completion must be initialized before tools that call compdef.
autoload -Uz compinit
compinit

# Prompt and shell navigation
eval "\$(starship init zsh)"
eval "\$(atuin init zsh)"
eval "\$(zoxide init zsh)"
source <(fzf --zsh)

# Better interactive editing
source "$brew_prefix/share/zsh-autosuggestions/zsh-autosuggestions.zsh"

# History
HISTFILE="\$HOME/.zsh_history"
HISTSIZE=100000
SAVEHIST=100000
setopt APPEND_HISTORY
setopt SHARE_HISTORY
setopt HIST_IGNORE_DUPS
setopt HIST_REDUCE_BLANKS
setopt AUTO_CD
setopt CORRECT

# Modern command aliases
alias ls='eza --icons'
alias ll='eza --icons --long --git --header'
alias la='eza --icons --long --git --header --all'
alias tree='eza --tree --icons'
alias cat='bat'
alias c='clear'
alias shrc='source ~/.zshrc'
alias ezsh='open -e ~/.zshrc'
alias eghost='open -e "\$HOME/Library/Application Support/com.mitchellh.ghostty/config.ghostty"'
alias estarship='open -e ~/.config/starship.toml'

# Git
alias g='git'
alias gs='git status'
alias gst='git status --short --branch'
alias ga='git add'
alias gaa='git add --all'
alias gc='git commit'
alias gp='git push'
alias gl='git pull'
alias gd='git diff'
alias gdc='git diff --cached'
alias gb='git branch'
alias gco='git checkout'
alias glog='git log --graph --decorate --oneline --all'
alias amend='git commit --amend --no-edit'
alias lg='lazygit'

# Laravel / Composer
alias art='php artisan'
alias pa='php artisan'
alias pam='php artisan migrate'
alias pamf='php artisan migrate:fresh'
alias pamfs='php artisan migrate:fresh --seed'
alias pat='php artisan test'
alias par='php artisan route:list'
alias pac='php artisan optimize:clear'
alias pint='./vendor/bin/pint'
alias sail='./vendor/bin/sail'
alias ci='composer install'
alias cu='composer update'
alias cda='composer dump-autoload'

# Node
alias ni='npm install'
alias nr='npm run'
alias nrd='npm run dev'
alias nrb='npm run build'
alias nrt='npm run test'

# Search
alias f='fd'
alias r='rg'

mkcd() {
  [[ -n "\${1:-}" ]] || { echo "Usage: mkcd <directory>"; return 1; }
  mkdir -p -- "\$1" && cd -- "\$1"
}

# Keep syntax highlighting last.
source "$brew_prefix/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"

$end_marker
ZSHRC
}

configure_git_delta() {
  log "Configuring Git Delta"
  git config --global core.pager delta
  git config --global interactive.diffFilter "delta --color-only"
  git config --global delta.navigate true
  git config --global delta.line-numbers true
  git config --global delta.side-by-side true
  git config --global merge.conflictStyle zdiff3
}

validate_setup() {
  log "Validating configuration"

  zsh -n "$HOME/.zshrc" || die "~/.zshrc contains a syntax error."

  if command -v starship >/dev/null 2>&1; then
    STARSHIP_CONFIG="$HOME/.config/starship.toml" starship explain >/dev/null || \
      die "Starship configuration validation failed."
  fi

  echo "Validation completed."
}

initialize_atuin() {
  if command -v atuin >/dev/null 2>&1 && [[ ! -f "$HOME/.local/share/atuin/history.db" ]]; then
    log "Importing existing shell history into Atuin"
    atuin import auto || warn "Atuin history import was skipped or failed."
  fi
}

print_summary() {
  cat <<EOF

Setup complete.

Active files:
  Ghostty:  $HOME/Library/Application Support/com.mitchellh.ghostty/config.ghostty
  Starship: $HOME/.config/starship.toml
  Zsh:      $HOME/.zshrc

Backups:
  $backup_dir

Next step:
  1. Fully quit and reopen Ghostty.
  2. Or run: exec zsh

Useful commands:
  lg         Lazygit
  Ctrl+R     Atuin history search
  z <name>   Smart directory jump
  shrc       Reload ~/.zshrc
  eghost     Edit Ghostty config
  estarship  Edit Starship config
EOF
}

main() {
  install_homebrew
  install_packages
  write_ghostty_config
  write_starship_config
  write_zsh_config
  configure_git_delta
  initialize_atuin
  validate_setup
  print_summary
}

main "$@"
